[workspace]
resolver = "2"
members = [

"deps/gnostr-cat",
"deps/gnostr-command",
"deps/gnostr-grep",
"deps/gnostr-sha256",

]

exclude = ["deps/gnostr-cli", "deps/gnostr-legit", "deps/gnostr-gossip"]

[profile.release]
debug = true
